import type { Metadata } from "next";
import "./globals.css";
import { noto, genei } from "./fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${genei.variable} ${noto.variable} antialiased`}
      >
        {children}
        <div className="mb-12"></div>
      </body>
    </html>
  );
}
